name: Scheduled Run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print Message
        run: echo "Running scheduled workflow"
